exclude: CHANGELOG.md

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-json
      - id: check-ast
      - id: check-xml
      - id: fix-byte-order-marker
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat-shfmt
  - repo: local
    hooks:
      - id: ormolu
        name: ormolu
        entry: ormolu
        language: system
        types: [haskell]
        args: [--mode=inplace]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.7
    hooks:
      - id: commitizen
