name:                prokki
version:             0.2.4
github:              "senysenyseny16/prokki"
license:             BSD-3-Clause
author:              "Arseny Yanchenko"
maintainer:          "arseny@protonmail.com"
copyright:           "2025 Arseny Yanchenko"

extra-source-files:
- README.md
- CHANGELOG.md
- LICENSE

description: Please see the README on GitHub at <https://github.com/senysenyseny16/prokki#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- wai-extra
- warp
- http-conduit
- http-types
- blaze-html
- network-uri
- conduit
- conduit-extra
- resourcet
- unliftio-core
- megaparsec
- replace-megaparsec
- mtl
- exceptions
- filepath
- directory
- bytestring
- containers
- text
- co-log
- co-log-concurrent
- tomland
- filemanip
- file-embed
- optparse-applicative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  - OverloadedStrings
  - BlockArguments
  - RecordWildCards
  - PatternSynonyms
  - TypeApplications
  - FlexibleContexts

library:
  source-dirs: src

executables:
  prokki:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prokki

tests:
  prokki-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prokki
