snapshot: lts-23.24
packages:
- .
notify-if-nix-on-path: false
extra-deps:
  - co-log-concurrent-0.5.1.0@sha256:1a4c36bb62a208af1da23b70c895259d401e3c58582ca3f88202a1e0e99bf59e,2824
allow-newer: true
allow-newer-deps:
  - co-log-concurrent
