name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ormolu:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: haskell-actions/run-ormolu@v14
